export const streetData = [
    "10th Avenue",
    "11th Avenue",
    "12th Avenue",
    "13th Avenue",
    "13th Street",
    "14th Avenue",
    "15th Avenue",
    "15th Street",
    "16th Avenue",
    "16th Street",
    "17th Avenue",
    "17th Street",
    "18th Avenue",
    "18th Street",
    "19th Avenue",
    "1st Avenue",
    "1st Street",
    "20th Street",
    "21st Avenue",
    "2nd Avenue",
    "2nd Street",
    "4th Street",
    "6th Street",
    "7th Street",
    "9th Avenue"
]