version: '3'
networks:
    sales-network:
      driver: bridge
services:
  psql:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_system_db
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_default.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - sales-network
  sss:
    image: 216995dce5e9
    container_name: server
    ports:
      - "3000:3000"
    expose:
      - 3000
    devices:
      - "/dev/usb:/dev/usb"
    networks:
      - sales-network
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@psql:5432/sales_system_db?schema=public
  ssv:
    image: 3745bbe597ed
    container_name: client
    ports:
      - "8080:8080"
    networks:
      - sales-network
    depends_on:
      - psql
      - sss